USE [master]
GO
/****** Object:  Database [eli_kantine]    Script Date: 05.03.2024 11:11:59 ******/
CREATE DATABASE [eli_kantine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eli_kantine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VG1\MSSQL\DATA\eli_kantine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'eli_kantine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VG1\MSSQL\DATA\eli_kantine_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [eli_kantine] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eli_kantine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [eli_kantine] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [eli_kantine] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [eli_kantine] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [eli_kantine] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [eli_kantine] SET ARITHABORT OFF 
GO
ALTER DATABASE [eli_kantine] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [eli_kantine] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [eli_kantine] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [eli_kantine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [eli_kantine] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [eli_kantine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [eli_kantine] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [eli_kantine] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [eli_kantine] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [eli_kantine] SET  DISABLE_BROKER 
GO
ALTER DATABASE [eli_kantine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [eli_kantine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [eli_kantine] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [eli_kantine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [eli_kantine] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [eli_kantine] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [eli_kantine] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [eli_kantine] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [eli_kantine] SET  MULTI_USER 
GO
ALTER DATABASE [eli_kantine] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [eli_kantine] SET DB_CHAINING OFF 
GO
ALTER DATABASE [eli_kantine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [eli_kantine] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [eli_kantine] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [eli_kantine] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'eli_kantine', N'ON'
GO
ALTER DATABASE [eli_kantine] SET QUERY_STORE = OFF
GO
USE [eli_kantine]
GO
/****** Object:  Table [dbo].[Meny]    Script Date: 05.03.2024 11:12:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Meny](
	[Dag] [nvarchar](50) NULL,
	[ProduktID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produkter]    Script Date: 05.03.2024 11:12:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produkter](
	[ProduktID] [int] IDENTITY(1,1) NOT NULL,
	[Kategori] [nvarchar](50) NULL,
	[Navn] [nvarchar](100) NULL,
	[Pris] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProduktID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProduktSalg]    Script Date: 05.03.2024 11:12:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProduktSalg](
	[PSID] [int] IDENTITY(1,1) NOT NULL,
	[ProduktID] [int] NULL,
	[SalgID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Salg]    Script Date: 05.03.2024 11:12:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Salg](
	[SalgID] [int] IDENTITY(1,1) NOT NULL,
	[Dato] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[SalgID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Meny]  WITH CHECK ADD FOREIGN KEY([ProduktID])
REFERENCES [dbo].[Produkter] ([ProduktID])
GO
ALTER TABLE [dbo].[ProduktSalg]  WITH CHECK ADD FOREIGN KEY([ProduktID])
REFERENCES [dbo].[Produkter] ([ProduktID])
GO
ALTER TABLE [dbo].[ProduktSalg]  WITH CHECK ADD FOREIGN KEY([SalgID])
REFERENCES [dbo].[Salg] ([SalgID])
GO
USE [master]
GO
ALTER DATABASE [eli_kantine] SET  READ_WRITE 
GO
